WIP improve build system

diff --git a/bin/buildify b/bin/buildify
--- a/bin/buildify
+++ b/bin/buildify
@@ -8,55 +8,46 @@
 ## The -e option forces bash to exit when encountering a non-zero exit status.
 ##   We omit -e as we do our own checking.
 set -u;
+## == BEGIN Layout variables
+_appName=$( basename $0 );
+_launchDir=$( pwd );
+echo "start ${_appName}";
+echo "  > layout vars";
 
-## == BEGIN Layout variables ===============================================
-  _appName=$( basename $0 );
-  _launchDir=$( pwd );
-  echo "start ${_appName}";
-  echo "  > layout vars";
+# app path and name
+_appLink=$( readlink -f -- "${0}" );
+_binDir=$( cd "${_appLink%/*}" && echo "${PWD}" );
 
-    # app path and name
-    _appLink=$( readlink -f -- "${0}" );
-    _binDir=$( cd "${_appLink%/*}" && echo "${PWD}" );
+# npm modules paths
+_npmDir=$( dirname "${_binDir}" );
+_modDir="${_npmDir}/node_modules";
+_modDirBin="${_modDir}/.bin";
 
-    # npm modules paths
-    _npmDir=$( dirname "${_binDir}" );
-    _modDir="${_npmDir}/node_modules";
-    _modDirBin="${_modDir}/.bin";
+_outDir="${_npmDir}/build";
+_topLogName="${_appName}.log";
+_topLogFile="${_npmDir}/${_topLogName}";
 
-    _outDir="${_npmDir}/build";
-    _topLogName="${_appName}.log";
-    _topLogFile="${_npmDir}/${_topLogName}";
+# cli varibles defaults
+_argBuildId='';
+_argDoHelp=0;
+_argDoVerbose=0;
+_argDontCompress=0;
+_stageDir='';
+_templateDir="${_npmDir}/tmplt";
+_tmpDir='';
 
-    # cli varibles defaults
-    _argDoHelp=0;
-    _argDoVerbose=0;
-    _argDontCompress=0;
-    _templateDir="${_npmDir}/tmplt";
+# executables
+_packExe="${_binDir}/superpack";
+_ugjsExe="${_modDirBin}/uglifyjs";
+_ugcssExe="${_modDirBin}/uglifycss";
 
-    # executables
-    _packExe="${_binDir}/superpack";
-    _ugjsExe="${_modDirBin}/uglifyjs";
-    _ugcssExe="${_modDirBin}/uglifycss";
-
-    # timestamps
-    _startTimestamp=$(date "+%Y-%m-%d %H:%M:%S");
-    _dateExt=$(date "+%Y%m%d_%H%M%S");
-
-    # temp dir
-    # See http://www.linuxsecurity.com/content/view/115462/81/#mozTocId440182
-    _tmpDir="${TMPDIR:-/tmp}/$$.${_appName}.${_dateExt}";
-    ( umask 077 && mkdir "${_tmpDir}" ) || {
-      _argDoVerbose=1;
-      _logFn "  ! Could not create temporary directory";
-      _abortFn;
-    }
-  # echo "  < layout vars";
-  ## == END Layout variables ===============================================
+# timestamps
+_startTimestamp=$(date "+%Y-%m-%d %H:%M:%S");
+_dateExt=$(date "+%Y%m%d_%H%M%S");
 
 ## BEGIN function to echo to STDERR
 _logStderrFn () { echo "$*" >&2; }
-## END function to echo to STDERR
+## . END function to echo to STDERR
 
 ## BEGIN function to print usage
 _showHelpFn () {
@@ -74,7 +65,7 @@ Employ the -v or --verbose switch to see more detailed help.
   [ "${_argDoVerbose}" -gt 0 ] && _logStderrFn "
 DESCRIPTION
   ${_appName} builds a production-ready web site from sources listed
-  in manifest files. The output files are placed in 
+  in manifest files. The output files are placed in
   ${_outDir}/<build_id> under the following subdirectories:
 
     - ${_outDir}/<build_id>/stage - Staging area
@@ -168,13 +159,13 @@ AUTHOR and COPYRIGHT
   Michael S. Mikowski (c) 2008-2016
 ";
 
-  exit 1;
+  exit 0;
 }
-## END function to print usage
+## . END function to print usage
 
 ## BEGIN function to log output
 _logFn () {
-  local IFS="";
+  local IFS='';
   _msg_str="$*";
   if [ -w "${_topLogFile}" ]; then
     echo "${_msg_str}" >> "${_topLogFile}";
@@ -185,7 +176,7 @@ _logFn () {
   if [ "${_argDoVerbose}" -gt 0 ]; then _logStderrFn "${_msg_str}"; fi
   return 0;
 }
-## END function to log output
+## . END function to log output
 
 ## BEGIN function to clean up temp files
 _cleanTmpdirFn () {
@@ -197,7 +188,7 @@ _cleanTmpdirFn () {
     fi
   fi
 }
-## END function to clean up temp files
+## . END function to clean up temp files
 
 ## BEGIN function to abort processing
 _abortFn () {
@@ -210,9 +201,21 @@ _abortFn () {
   # exit with error (bash shell standard)
   exit 1;
 }
-## END function to abort processing
+## . END function to abort processing
 
 ## BEGIN MAIN
+_main () {
+    # temp dir
+    # See http://www.linuxsecurity.com/content/view/115462/81/#mozTocId440182
+    _tmpDir="${TMPDIR:-/tmp}/$$.${_appName}.${_dateExt}";
+    ( umask 077 && mkdir "${_tmpDir}" ) || {
+      _argDoVerbose=1;
+      _logFn "  ! Could not create temporary directory";
+      _abortFn;
+    }
+  # echo "  < layout vars";
+  ## == END Layout variables
+
   ## BEGIN get options
   ## (see /usr/share/doc/util-linux/examples/getopt-parse.bash)
   _cliStr=$(getopt -o hnvi: \
@@ -241,20 +244,21 @@ _abortFn () {
           _abortFn;;
     esac
   done
+  ## . END get options
 
+  ## BEGIN process options
   if [ ${_argDoHelp} -gt 0 ]; then _showHelpFn; fi
-  ## END get options
-
   if [ -z "${_argBuildId}" ]; then
-    _logStderrFn "Please provide build id like so: -i 12345";
+    _logStderrFn "Please provide a build id like so: -i 12345";
     _abortFn;
   fi
+  ## . END process options
 
   _buildDir="${_outDir}/${_argBuildId}"
   _distDir="${_buildDir}/dist";
   _stageDir="${_buildDir}/stage";
 
-  ## BEGIN set global log to start
+  ## BEGIN set global files and directories
   if ! echo -n > "${_topLogFile}"; then
     _argDoVerbose=1;
     _logStderrFn "Cannot create global log file '${_topLogFile}'";
@@ -262,7 +266,7 @@ _abortFn () {
   fi
   # put header in log file
   _logFn "  > Global ${_appName} log ${_startTimestamp}";
-  ## END set global log to start
+  ## . END set global files and directories
 
   ## BEGIN Find SuperPack
   if [ ! -x "${_packExe}" ]; then
@@ -279,7 +283,7 @@ _abortFn () {
     _logfn "  !    liblist-moreutils-perl libgetopt-mixed-perl ";
     _abortFn;
   fi
-  ## END Find SUPERPACK
+  ## . END Find SUPERPACK
 
   ## BEGIN Find UglifyJS
   if [ ! -x "${_ugjsExe}" ]; then
@@ -290,7 +294,7 @@ _abortFn () {
     _logFn "  ! as described by ${_appName} -hv"
     _abortFn;
   fi
-  ## END Find UglifyJS
+  ## . END Find UglifyJS
 
   ## BEGIN Find UglifyCSS
   if [ -z "${_ugcssExe}" ]; then
@@ -299,12 +303,10 @@ _abortFn () {
     _logFn "  ! Try cd ${_npmDir}; npm install uglifycss -D"
     _abortFn;
   fi
-  ## END Find UglifyCSS
+  ## . END Find UglifyCSS
 
   ## BEGIN validiate input files
   _manifestList=();
-  _copyDeployList=();
-  _subtreeDeployList=();
   for _arg_file in $@; do
     if [ ! -f "${_arg_file}" ]; then
       _argDoVerbose=1;
@@ -327,7 +329,7 @@ _abortFn () {
     _logFn "  ! No manifest provided."
     _abortFn;
   fi
-  ## END validiate input files
+  ## . END validiate input files
 
   ## BEGIN validate build dir and move global log to it
   mkdir -p "${_outDir}";
@@ -341,7 +343,7 @@ _abortFn () {
       _logFn "  ! Aborted at user request.";
       _abortFn;
     fi
-    _logFn "";
+    _logFn '';
     _logFn "  > Removing ${_buildDir} at user request";
     rm -rf "${_buildDir}";
     _logFn "  > Removal complete.";
@@ -372,7 +374,7 @@ _abortFn () {
   else
     _topLogFile="${_buildDir}/${_topLogName}";
   fi
-  ## END validate build dir and move global log there
+  ## . END validate build dir and move global log there
 
   ## BEGIN process each manifest in turn
   for (( _file_idx = 0; _file_idx < ${#_manifestList[*]}; _file_idx++ )); do
@@ -380,8 +382,8 @@ _abortFn () {
     _manifest_file="${_manifestList[$_file_idx]}";
     _manifest_basename=$( basename "${_manifest_file}" );
     _manifest_short_name=$( echo "${_manifest_basename}" |cut -f1 -d'.' );
-    _manifest_dir=$( dirname "${_manifest_file}" );
-    _manifest_dir=$( cd "${_manifest_dir}" && echo "${PWD}" );
+#    _manifest_dir=$( dirname "${_manifest_file}" );
+#    _manifest_dir=$( cd "${_manifest_dir}" && echo "${PWD}" );
 
     if [ -z "${_manifest_short_name}" ]; then
       _argDoVerbose=1;
@@ -390,22 +392,20 @@ _abortFn () {
     fi
 
     _logFn "  > ${_appName}  for ${_manifest_file} on ${_startTimestamp}";
-    ## END get path of manifest and determine output names
+    ## . END get path of manifest and determine output names
 
     ## BEGIN read manifest and append sources to arrays
     _js_file_list=();
     _css_file_list=();
-    _section_type="";
+    _copy_deploy_list=();
+    _subtree_deploy_list=();
+    _section_type='';
 
     while read _row_str; do
       # skip blank lines
       echo "${_row_str}" | grep -q '^\s*$' && continue;
       # skip full-line comments
       echo "${_row_str}" | grep -q '^\s*#' && continue;
-
-      # strip end of line comments and indents
-      _row_str=$(echo "${_row_str}" | sed -e 's/#.*$//g' \
-        | sed -e 's/^\s\+//g' | sed -e 's/\s\+$//g' );
 
       # process section header 'sourcetype'
       if echo "${_row_str}" | grep -q '^sourcetype\s*:'; then
@@ -415,55 +415,54 @@ _abortFn () {
       fi
 
       # skip anything if section type not yet specified
-      [ "${_section_type}" == "" ] && continue;
+      [ "${_section_type}" == '' ] && continue;
+
+      # strip end of line comments and indents
+      _row_str=$(echo "${_row_str}" | sed -e 's/#.*$//g' \
+        | sed -e 's/^\s\+//g' | sed -e 's/\s\+$//g' );
+
+      # determine first field, file extension, full-qualified source_file
+      _field1_str=$( echo "${_row_str}" |sed -e 's/\s.*$//g' );
+      _ext_str=$( echo ${_field1_str} |sed -e 's/^.*\.//' );
+      _source_file="${_npmDir}/${_field1_str}";
 
       # determine full path to source file and test
-      _source_file="${_manifest_dir}/${_row_str}";
-
-      if [ "${_section_type}" = "css" ] || [ "${_section_type}" = "js" ]; then
-        if [ ! -r "${_source_file}" ]; then
-          _argDoVerbose=1;
-          _logFn "  ! ${_section_type} file ${_source_file} is not readable.";
-          _logFn "  ! Do you need to update your manifest file?";
-          _logFn "  ! X_${_row_str}_X";
-          _abortFn;
-        fi
+      if [ ! -r "${_source_file}" ]; then
+        _argDoVerbose=1;
+        _logFn "  ! ${_section_type} file ${_source_file} is not readable.";
+        _logFn "  ! Do you need to update your manifest file?";
+        _logFn "  ! X_${_field1_str}_X";
+        _abortFn;
       fi
-      _ext_str=$( echo ${_row_str} |sed -e 's/^.*\.//' );
 
       case "${_section_type}" in
         js)
           if [ "${_ext_str}" != 'js' ]; then
             _argDoVerbose=1;
-            _logFn "  > Extension for js file ${_row_str} must be 'js'";
+            _logFn "  > Extension for js file ${_field1_str} must be 'js'";
             _abortFn;
           fi
 
-          _js_file_list[${#_js_file_list[*]}]=${_source_file};
-            _logFn "  > Added file ${_row_str} to javascript processing queue.";
+          _js_file_list[${#_js_file_list[*]}]="${_source_file}";
+            _logFn "  > Added file ${_field1_str} to JS queue."
           ;;
 
         css)
           if [ "${_ext_str}" != 'css' ]; then
             _argDoVerbose=1;
-            _logFn "  ! Extension for css file ${_row_str} must be 'css'";
+            _logFn "  ! Extension for css file ${_field1_str} must be 'css'";
             _abortFn;
           fi
-
-          _css_file_list[${#_css_file_list[*]}]=${_source_file};
-          _logFn "  > Added file ${_row_str} to css processing queue.";
+          _css_file_list[${#_css_file_list[*]}]="${_source_file}";
+          _logFn "  > Added file ${_field1_str} to CSS queue.";
           ;;
         subtree)
-          _subtreeDeployList[${#_css_file_list[*]}]=${_source_file};
-          _scratchStr="${_argDoVerbose}"; _argDoVerbose=1;
-          # _logFn "  ! deploy subtree not yet implemented ${_row_str}";
-          _argDoVerbose="${_scratchStr}";
+          _subtree_deploy_list[${#_subtree_deploy_list[*]}]="${_source_file}";
+          _logFn "  > Added file ${_field1_str} to SUBTREE DEPLOY queue.";
           ;;
         copy)
-          _copyDeployList[${#_css_file_list[*]}]=${_source_file};
-          _scratchStr="${_argDoVerbose}"; _argDoVerbose=1;
-          # _logFn "  ! deploy copy not yet implemented ${_row_str}";
-          _argDoVerbose="${_scratchStr}";
+          _copy_deploy_list[${#_copy_deploy_list[*]}]="${_row_str}"
+          _logFn "  > Added row ${_row_str} to COPY DEPLOY queue.";
           ;;
         *) _argDoVerbose=1;
           _logFn "  ! Source type (${_section_type}) not supported.";
@@ -471,7 +470,7 @@ _abortFn () {
           ;;
       esac
     done < "${_manifest_file}"
-    ## END read manifest and append sources to arrays
+    ## . END read manifest and append sources to arrays
 
     ## BEGIN determine paths
     _js_concat_file="${_tmpDir}/$$.${_manifest_short_name}-src.js";
@@ -490,7 +489,7 @@ _abortFn () {
     _ugjs_out_file="${_stage_base_name}-min.js";
     _pack_out_file="${_stage_base_name}-sp.js";
     touch "${_pack_log_file}";
-    ## END determine paths
+    ## . END determine paths
 
 
     ## BEGIN process javascript files
@@ -509,7 +508,7 @@ _abortFn () {
       cat "${_js_file_list[$i]}" >> "${_js_concat_file}";
       _logFn "  > ${_js_file_list[$i]}";
     done
-    ## END process javascript files
+    ## . END process javascript files
 
     ## BEGIN compress javascript file if specified
     if [ -r "${_js_concat_file}" ] && [ ${_argDontCompress} -eq 0 ]; then
@@ -530,7 +529,7 @@ _abortFn () {
         _abortFn;
       fi
     fi
-    ## END compress javascript file if specified
+    ## . END compress javascript file if specified
 
     ## BEGIN superpack javascript file if specified
     if [ -r "${_js_concat_file}" ] && [ ${_argDontCompress} -eq 0 ]; then
@@ -550,7 +549,7 @@ _abortFn () {
         _abortFn;
       fi
     fi
-    ## END superpack javascript file if specified
+    ## . END superpack javascript file if specified
 
     ## BEGIN process css files
     for (( i = 0; i < ${#_css_file_list[*]}; i++ ))
@@ -569,7 +568,7 @@ _abortFn () {
       cat "${_css_file_list[$i]}" >> "${_css_concat_file}";
       _logFn "  >> ${_css_file_list[$i]}";
     done
-    ## END process css files
+    ## . END process css files
 
     ## BEGIN compress css file if specified
     if [ -r "${_css_concat_file}" ] && [ ${_argDontCompress} -eq 0 ]; then
@@ -590,7 +589,7 @@ _abortFn () {
         _abortFn;
       fi
     fi
-    ## END compress css file if specified
+    ## . END compress css file if specified
 
     ## BEGIN move over remaining files
     for _pair_str in \
@@ -608,24 +607,59 @@ _abortFn () {
         fi
       fi
     done
-    ## END move over remaining files
+    ## . END move over remaining files
 
     ## BEGIN deployment (WIP)
-    pushd "${_distDir}";
-    cp "${_templateDir}/${_manifest_short_name}.html" "${_distDir}/"
-    cp -a "${_npmDir}"/font/vendor/* "${_distDir}/font/vendor/"
     cp "${_pack_out_file}" "${_distDir}/js/"
     cp "${_ugcss_out_file}" "${_distDir}/css/"
-    popd;
-    ## END deployment (WIP)
+
+    ## BEGIN subtree deployment
+    for (( i = 0; i < ${#_subtree_deploy_list[*]}; i++ ))
+    do
+      _row_str="${_subtree_deploy_list[$i]}";
+      _dirname=$( dirname "${_row_str}" );
+      _src_dir="${_npmDir}/${_row_str}";
+      _tgt_dir="${_distDir}/${_dirname}";
+
+      if [ ! -d "${_src_dir}" ]; then
+        _logFn "Cannot copy subtree |${_row_str}|: Not found";
+        continue;
+      fi
+
+      mkdir -p "${_tgt_dir}";
+      cp -a "${_src_dir}" "${_tgt_dir}";
+    done
+    ## . END subtree deployment
+
+    ## BEGIN copy deployment
+    for (( i = 0; i < ${#_copy_deploy_list[*]}; i++ ))
+    do
+      _row_str="${_copy_deploy_list[$i]}";
+      echo ">>>> $_row_str";
+      _dirname=$( dirname "${_row_str}" );
+      _src_file="${_npmDir}/${_row_str}";
+      _tgt_dir="${_distDir}/${_dirname}";
+      _tgt_file="${_distDir}/${_row_str}";
+
+      if [ ! -f "${_src_dir}" ]; then
+        _logFn "Cannot copy file |${_row_str}|: Not found";
+        continue;
+      fi
+
+      mkdir -p "${_tgt_dir}";
+      cp "${_src_file}" "${_tgt_file}";
+    done
 
   done
-  ## END process each manifest in turn
+  ## . END process each manifest in turn
 
   _cleanTmpdirFn;
   _endTimestamp=$(date "+%Y-%m-%d %H:%M:%S");
   _logFn "  > ${_appName} run complete on ${_endTimestamp}";
   echo "end ${_appName}";
-## END MAIN
+}
+## . END MAIN
+
+_main $@;
 
 
