Added superpack; updated commit hook

diff --git a/bin/git-hook_pre-commit b/bin/git-hook_pre-commit
--- a/bin/git-hook_pre-commit
+++ b/bin/git-hook_pre-commit
@@ -12,19 +12,23 @@ set -u;
 # (disabled here as we do are own checking)
 # set -e;
 
-# Adjust for links
+## BEGIN Layout variables ==================================================
 LINK_PATH=$(readlink -f -- "${0}");
-BIN_PATH=$( cd ${LINK_PATH%/*} && echo $PWD ); # absolute path to this bin
+BIN_PATH=$(cd ${LINK_PATH%/*} && echo $PWD); # absolute path to this bin
 ROOT_DIR=$(cd "$(git rev-parse --show-toplevel)" && pwd );
+JSLINT_EXEC="${ROOT_DIR}/node_modules/jslint/bin/jslint.js";
+NODE_EXEC=$(which node);
+NODEUNIT_EXEC="${ROOT_DIR}/node_modules/nodeunit/bin/nodeunit";
+NODEUNIT_FILE="${ROOT_DIR}/test/t.js";
+MAKEDOC_EXEC="${ROOT_DIR}/bin/make_doc";
+TMP_FILE="/tmp/git-pre-commit.${$}tmp";
+## END Layout variables ====================================================
 
-# TODO later: JSLINT_EXEC="${ROOT_DIR}/node_modules/jslint/bin/jslint.js";
-JSLINT_TMP_FILE="/tmp/git-pre-commit.tmp";
-JSLINT_EXEC=$(which jslint);
-if [ ! -x "${JSLINT_EXEC}" ]; then
-  echo "JSLint not found."
+## BEGIN Lint JavaScript files =============================================
+if [ ! -x "${JSLINT_EXEC}" ] || [ ! -x "${NODEUNIT_EXEC}" ]; then
+  echo "Development libraries not found."
   echo "Please execute the following command: "
-  # TODO later: echo "  cd ${ROOT_DIR}; npm install ";
-  echo "  npm install -g jslint";
+  echo "  cd ${ROOT_DIR}; npm install ";
   exit 1;
 fi
 
@@ -34,7 +38,7 @@ echo "  We ignore vendor libraries in .../vendor/...";
 git status \
   | grep '.js$' \
   | grep -v '/vendor/' \
-  | grep -v 'pcss._ex004_.js' \
+
   | grep '^\s\+\(modified\|new file\)' \
   | cut -d ":" -f 2- \
   | while read LINE; do
@@ -49,57 +53,61 @@ git status \
         echo "pass";
       fi;
     done \
-  | tee "${JSLINT_TMP_FILE}";
+  | tee "${TMP_FILE}";
 
 echo "JSLint test complete";
-if grep -s 'FAIL' "${JSLINT_TMP_FILE}"; then
+if grep -s 'FAIL' "${TMP_FILE}"; then
   echo "FAIL: JSLint checks did not pass.";
   echo "  Please use jslint to test the problem files and ";
   echo "  commit again once they pass the check.";
-  rm "${JSLINT_TMP_FILE}";
+  rm "${TMP_FILE}";
   exit 1;
 fi
 
-rm "${JSLINT_TMP_FILE}";
+rm "${TMP_FILE}";
 echo;
+## END Lint JavaScript files ===============================================
 
-
+## BEGIN Progress changed documents ========================================
 ## TODO
-# MAKEDOC_EXEC="${ROOT_DIR}/bin/make_doc";
-# if [ ! -x "${MAKEDOC_EXEC}" ]; then
-#   echo "bin/make_doc not found.  This file should exist.";
-#   echo "Please check your installation.";
-#   exit 1;
-# fi
-# echo "Updating HTML documents from MarkDown";
-# "${MAKEDOC_EXEC}";
+##  if [ ! -x "${MAKEDOC_EXEC}" ]; then
+##    echo "bin/make_doc not found.  This file should exist.";
+##    echo "Please check your installation.";
+##    exit 1;
+##  fi
+##  echo "Updating HTML documents from MarkDown";
+##  "${MAKEDOC_EXEC}";
+##  RET_VAL=$?;
+##  if [ "${RET_VAL}" -eq "0" ]; then
+##    echo "Document file failure".
+##    echo "Please check your installation.";
+##    exit "${RET_VAL}";
+##  fi
+##
+## END Progress changed documents ==========================================
 
+## BEGIN Run regression tests ==============================================
 ## TODO
-# NODE_EXEC=$(which node);
-# NODEUNIT_EXEC="${ROOT_DIR}/node_modules/nodeunit/bin/nodeunit";
-# NODEUNIT_FILE="${ROOT_DIR}/client/test/t.js";
-# if [ ! -x "${NODE_EXEC}" ]; then
-#   echo "Node not found.  Please install nodejs and ensure it is "
-#   echo " found in your PATH environment variable."
-#   exit 1;
-# fi
-# 
-# if [ ! -x "${NODEUNIT_EXEC}" ]; then
-#   echo "Nodeunit not found.  Please run "
-#   echo "cd ${ROOT_DIR}; npm install"
-#   echo
-# fi
-# 
-# if [ ! -x "${NODEUNIT_FILE}" ]; then
-#   echo "Nodeunit file ${NODEUNIT_FILE}" not found."
-#   echo "Please ensure it exists."
-#   echo
-#   exit 1;
-# fi
-
-
-## TODO
-# echo "Running regression tests";
-# "${NODEUNIT_EXEC}" "${NODEUNIT_FILE}"
-# exit $?;
-
+## if [ ! -x "${NODE_EXEC}" ]; then
+##   echo "Node not found.  Please install nodejs and ensure it is "
+##   echo " found in your PATH environment variable."
+##   exit 1;
+## fi
+##
+## if [ ! -x "${NODEUNIT_EXEC}" ]; then
+##   echo "Nodeunit not found.  Please run "
+##   echo "cd ${ROOT_DIR}; npm install"
+##   echo
+## fi
+##
+## if [ ! -r "${NODEUNIT_FILE}" ]; then
+##   echo "Nodeunit file ${NODEUNIT_FILE} not found."
+##   echo "Please ensure it exists."
+##   echo
+##   exit 1;
+## fi
+##
+## echo "Running regression tests";
+## "${NODEUNIT_EXEC}" "${NODEUNIT_FILE}"
+## exit $?;
+## END Run regression tests ================================================
