New, more portable pre-commit hook

diff --git a/bin/git-hook_pre-commit b/bin/git-hook_pre-commit
--- a/bin/git-hook_pre-commit
+++ b/bin/git-hook_pre-commit
@@ -13,62 +13,83 @@ set -u;
 # set -e;
 
 ## BEGIN Layout variables ==================================================
-LINK_PATH=$(readlink -f -- "${0}");
-BIN_PATH=$(cd ${LINK_PATH%/*} && echo $PWD); # absolute path to this bin
-ROOT_DIR=$(cd "$(git rev-parse --show-toplevel)" && pwd );
-JSLINT_EXEC="${ROOT_DIR}/node_modules/jslint/bin/jslint.js";
 NODE_EXEC=$(which node);
-NODEUNIT_EXEC="${ROOT_DIR}/node_modules/nodeunit/bin/nodeunit";
-NODEUNIT_FILE="${ROOT_DIR}/test/t.js";
-MAKEDOC_EXEC="${ROOT_DIR}/bin/make_doc";
-TMP_FILE="/tmp/git-pre-commit.${$}tmp";
+LINK_PATH=$(readlink -f -- "${0}");
+BIN_PATH=$(cd "${LINK_PATH%/*}" && echo "${PWD}");
+GIT_DIR=$(cd "$(git rev-parse --show-toplevel)" && pwd );
+PKG_DIR=$(find "${GIT_DIR}" -type f -name 'package.json' |head -n1);
+MODS_DIR=$(find "${GIT_DIR}" -type d -name 'node_modules' |head -n1);
+WAPP_DIR=$(dirname "${MODS_DIR}");
+JSLINT_EXEC="${MODS_DIR}/.bin/jslint";
+NU_EXEC="${MODS_DIR}/.bin/nodeunit";
+NU_FILE="${WAPP_DIR}/test/nu_xhi.util.js";
+MAKEDOC_EXEC="${GIT_DIR}/bin/make_doc";
+LIST_FILE="/tmp/git-pre-commit.${$}.list.tmp";
+TMP_FILE="/tmp/git-pre-commit.${$}.tmp";
+CHECK_STR="";
 ## END Layout variables ====================================================
 
 ## BEGIN Lint JavaScript files =============================================
-if [ ! -x "${JSLINT_EXEC}" ] || [ ! -x "${NODEUNIT_EXEC}" ]; then
-  echo "Development libraries not found."
+if [ ! -x "${JSLINT_EXEC}" ]; then
+  echo "JSLint executable not found."
   echo "Please execute the following command: "
-  echo "  cd ${ROOT_DIR}; npm install ";
+  echo "  cd ${GIT_DIR}; npm install ";
   exit 1;
 fi
 
-echo;
-echo "JSLint test of updated or new *.js files ...";
-echo "  We ignore vendor libraries in .../vendor/...";
 git status \
-  | grep '.js$' \
+  | grep '.*.js' \
   | grep -v '/vendor/' \
-
   | grep '^\s\+\(modified\|new file\)' \
-  | cut -d ":" -f 2- \
-  | while read LINE; do
-      echo -en "  Check ${LINE}: ... "
-      CHECK_STR=$(${JSLINT_EXEC} ${LINE});
-      CHECK_CODE=$?;
-      echo "${CHECK_CODE}"
-      if [ "${CHECK_CODE}" -gt 0 ]; then
-        echo "${LINE} JSLint check FAILED";
-        echo "${CHECK_STR}";
-      else
-        echo "pass";
-      fi;
-    done \
-  | tee "${TMP_FILE}";
+  | cut -d ":" -f 2- > "${LIST_FILE}"
 
-echo "JSLint test complete";
-if grep -s 'FAIL' "${TMP_FILE}"; then
-  echo "FAIL: JSLint checks did not pass.";
-  echo "  Please use jslint to test the problem files and ";
-  echo "  commit again once they pass the check.";
+echo;
+echo "Tests of updated or new *.js files ...";
+cat "${LIST_FILE}" | while read FILE_NAME; do
+  echo "====> ${FILE_NAME}";
+  CHECK_STR=$(${JSLINT_EXEC} "${FILE_NAME}");
+  CHECK_CODE=$?;
+  if [ "${CHECK_CODE}" -gt 0 ]; then
+    echo "  JSLint check FAILED";
+    echo "  ${CHECK_STR}";
+  fi;
+  CHECK_STR=$(grep -nP '\t' "${FILE_NAME}");
+  if [ ! -z "${CHECK_STR}" ]; then
+    echo "  Tab check FAILED";
+    echo "  ${CHECK_STR}";
+    echo;
+  fi
+  CHECK_STR=$(grep -nP '\s+$' ${FILE_NAME});
+  if [ ! -z "${CHECK_STR}" ]; then
+    echo "  Trailing space check FAILED";
+    echo "  ${CHECK_STR}";
+    echo;
+  fi
+  CHECK_STR=$(grep '^\s*.use strict.;$' ${FILE_NAME});
+  if [ -z "${CHECK_STR}" ]; then
+    echo "  Strict use check FAILED";
+    echo "  Please add 'use strict'; at the top of your module function.";
+    echo;
+  fi
+  echo "<====";
+  echo;
+done | tee "${TMP_FILE}";
+
+echo "Tests complete";
+if grep -qs 'FAIL' "${TMP_FILE}"; then
+  echo "Checks did not pass.";
+  echo "  Please fix the problem files and commit again.";
   rm "${TMP_FILE}";
   exit 1;
 fi
 
 rm "${TMP_FILE}";
+rm "${LIST_FILE}";
+
 echo;
 ## END Lint JavaScript files ===============================================
 
-## BEGIN Progress changed documents ========================================
+## BEGIN Process changed documents ========================================
 ## TODO
 ##  if [ ! -x "${MAKEDOC_EXEC}" ]; then
 ##    echo "bin/make_doc not found.  This file should exist.";
@@ -84,30 +105,29 @@ echo;
 ##    exit "${RET_VAL}";
 ##  fi
 ##
-## END Progress changed documents ==========================================
+## END Process changed documents ==========================================
 
 ## BEGIN Run regression tests ==============================================
-## TODO
-## if [ ! -x "${NODE_EXEC}" ]; then
-##   echo "Node not found.  Please install nodejs and ensure it is "
-##   echo " found in your PATH environment variable."
-##   exit 1;
-## fi
-##
-## if [ ! -x "${NODEUNIT_EXEC}" ]; then
-##   echo "Nodeunit not found.  Please run "
-##   echo "cd ${ROOT_DIR}; npm install"
-##   echo
-## fi
-##
-## if [ ! -r "${NODEUNIT_FILE}" ]; then
-##   echo "Nodeunit file ${NODEUNIT_FILE} not found."
-##   echo "Please ensure it exists."
-##   echo
-##   exit 1;
-## fi
-##
-## echo "Running regression tests";
-## "${NODEUNIT_EXEC}" "${NODEUNIT_FILE}"
-## exit $?;
+if [ ! -x "${NODE_EXEC}" ]; then
+  echo "Node not found.  Please install nodejs and ensure it is "
+  echo " found in your PATH environment variable."
+  exit 1;
+fi
+
+if [ ! -x "${NU_EXEC}" ]; then
+  echo "Nodeunit not found.  Please run "
+  echo "cd ${GIT_DIR}; npm install"
+  echo
+fi
+
+if [ ! -r "${NU_FILE}" ]; then
+  echo "Nodeunit file ${NU_FILE} not found."
+  echo "Please ensure it exists."
+  echo
+  exit 1;
+fi
+
+echo "Running regression tests";
+"${NU_EXEC}" "${NU_FILE}"
+exit $?;
 ## END Run regression tests ================================================
